### ISSUE TITLE
Anexa: Lista deplasari

### ISSUE THREAD

**Issue by DarianTUDOR** [babatudor/ProjectRaven#16]
**Development:**
- [x]  vizualizare lista deplasari
- [x]  adaugarea unei deplasari
- [x]  editarea unei deplasari
- [x]  stergerea unei deplasari

**Code review:**
- [x] code review intern
- [x] code review extern

**Validation:**
- [ ] Locul deplasarii ? 
- [ ] Scopul deplasarii ?
- [ ] Valoarea ?

**Testing:**
- [x] teste unitare

**Comment by babatudor** [comment]
![image](https://user-images.githubusercontent.com/2479929/68471804-a4cb7a00-0227-11ea-8e23-2041532541ae.png)
