### ISSUE TITLE
Deviz Antecalcul

### ISSUE THREAD

**Issue by Gainar** [babatudor/ProjectRaven#9]
**Development**
- [x] Afisare lista devize
- [x] Vizualizarea unui deviz
- [x] Editarea unui deviz
- [x] Stergerea unui deviz

**Code review**
- [x] Review intern
- [ ] Review extern

**Testing**
- [x] Unit testing

**Comment by babatudor** [comment]
![image](https://user-images.githubusercontent.com/2479929/68484413-e2d79680-0245-11ea-9395-b1401d42a2bc.png)
